#!/bin/bash
#

debug()
{
if [ "$debug" == "1" ]; then
    d=$1
    echo $d
fi
}
usage()
{
    echo "usage: eclipse-pvs [[-w <path> -n <name> [-d]]| -h]"
    echo "where args:"
    echo "      -w(--workspace)   <path>    set path to workspace directory"
    echo "      -n(--projectname) <name>    project name in eclipse"
    echo "      -c(--config)      <config>  config descriptor (Debug or Release)"
    echo "      -d(--debug)                 some debuging info"
    echo "      -h(--help)                  show this message"
}

clean ()
{
debug "Clean"
make -f makefile clean
   # Nothing to do
    exit
}

analyze()
{
    debug "running command:"
    debug "/usr/local/bin/docker run --security-opt seccomp:\"""$workspace/docker-pvs/strace.json""\" -v \"""$workspace""\":/root/workspace -i timurey/docker-pvs /root/workspace/docker-pvs/client -n \"""$projectname""\" -c \"""$config""\""
    /usr/local/bin/docker run --security-opt seccomp:"$workspace/docker-pvs/strace.json" -v "$workspace":/root/workspace -i timurey/docker-pvs /root/workspace/docker-pvs/client -n "$projectname" -c "$config"
    exit
}

while [ "$1" != "" ]; do
    case $1 in
        -w | --workspace )      shift
				workspace=$1
                                ;;
        -c | --config )         shift
				config=$1
                                ;;
        -n | --projectname )    shift
                projectname=$1
                                ;;
        -d | --debug )          
                debug=1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        clean )                 clean
                                exit 1
    esac
    shift
done

debug "$PWD"
if [ "$workspace" != "" ]; then
    if [ "$projectname" != "" ]; then
        if [ "$config" != "" ]; then
    debug "workspace path: \"$workspace\""
    debug "project name: \"$projectname\""
    debug "config description: \"$config\""
    analyze
        else
            echo "config description is not defined" >&2
            exit
        fi
    else
        echo "project name path is not defined" >&2
        exit
    fi
else
    echo "workspace is not defined" >&2
    exit
fi
